[package]
name = "ssh-migrator-cli"
version = "0.1.0"
edition = "2021"
default-run = "sshmigrate"

[[bin]]
name = "sshmigrate"
path = "src/main.rs"

[dependencies]
ssh-migrator-protocol = { path = "../protocol" }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
snow = { workspace = true }
rand = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
zeroize = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4", features = ["derive"] }
zstd = "0.13"
tar = "0.4"
walkdir = "2"
